# Generated by Django 2.2.10 on 2020-03-06 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.TextField(verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('alpha2', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True, verbose_name='ISO3166-1-Alpha-2')),
                ('alpha3', models.CharField(max_length=3, unique=True, verbose_name='ISO3166-1-Alpha-3')),
                ('dial', models.TextField(verbose_name='Dial')),
                ('name', models.TextField(verbose_name='UNTERM English Formal')),
                ('continent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Continent', verbose_name='Continent')),
                ('capital', models.TextField(verbose_name='Capital')),
            ],
        ),
    ]
