# Generated by Django 2.2.10 on 2020-03-06 23:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.TextField(verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('alpha2', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True, verbose_name='ISO3166-1-Alpha-2')),
                ('alpha3', models.CharField(max_length=3, unique=True, verbose_name='ISO3166-1-Alpha-3')),
                ('dial', models.TextField(verbose_name='Dial')),
                ('name', models.TextField(verbose_name='UNTERM English Formal')),
                ('continent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Continent', verbose_name='Continent')),
                ('capital', models.TextField(verbose_name='Capital')),
                ('ds', models.CharField(default='', max_length=3, verbose_name='DS')),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None, verbose_name='Languages')),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('ident', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='ident')),
                ('type', models.TextField(verbose_name='type')),
                ('name', models.TextField(verbose_name='name')),
                ('elevation', models.FloatField(null=True, verbose_name='elevation_ft')),
                ('gps_code', models.CharField(max_length=4, verbose_name='gps_code')),
                ('iata_code', models.CharField(max_length=3, verbose_name='iata_code')),
                ('latitude', models.FloatField(verbose_name='coordinates')),
                ('longitude', models.FloatField(verbose_name='coordinates')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Continent', verbose_name='continent')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Country', verbose_name='iso_country')),
            ],
        ),
    ]
