# Generated by Django 2.2.10 on 2020-03-10 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Currency')),
                ('code', models.CharField(max_length=3, verbose_name='AlphabeticCode')),
                ('withdrawal_date', models.DateField(null=True, verbose_name='WithdrawalDate')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Country', verbose_name='Entity')),
            ],
        ),
    ]
