# Generated by Django 2.2.10 on 2020-03-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='ds',
            field=models.CharField(default='', max_length=3, verbose_name='DS'),
            preserve_default=False,
        ),
    ]
