# Generated by Django 2.2.10 on 2020-03-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='original_title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
