# Generated by Django 2.2.10 on 2020-03-06 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_title_original_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('alpha2', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('alpha3', models.CharField(max_length=3, unique=True)),
                ('dial', models.CharField(max_length=6)),
                ('name', models.TextField()),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Continent')),
            ],
        ),
    ]
