# Generated by Django 2.2.10 on 2020-02-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_person_personnel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='birthYear',
            new_name='birth_year',
        ),
    ]
