# Generated by Django 2.2.10 on 2020-03-06 21:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_country_ds'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
    ]
