# Generated by Django 2.2.10 on 2020-03-06 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_continent_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.TextField(default='', verbose_name='Capital'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='continent',
            name='code',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='name',
            field=models.TextField(verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='alpha2',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, unique=True, verbose_name='ISO3166-1-Alpha-2'),
        ),
        migrations.AlterField(
            model_name='country',
            name='alpha3',
            field=models.CharField(max_length=3, unique=True, verbose_name='ISO3166-1-Alpha-3'),
        ),
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Continent', verbose_name='Continent'),
        ),
        migrations.AlterField(
            model_name='country',
            name='dial',
            field=models.CharField(max_length=6, verbose_name='Dial'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.TextField(verbose_name='Global Name'),
        ),
    ]
