# Generated by Django 2.2.10 on 2020-03-06 22:11

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_country_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None, verbose_name='Languages'),
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('ident', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='ident')),
                ('type', models.TextField(verbose_name='type')),
                ('name', models.TextField(verbose_name='name')),
                ('elevation', models.IntegerField(verbose_name='elevation_ft')),
                ('gps_code', models.CharField(max_length=4, verbose_name='gps_code')),
                ('iata_code', models.CharField(max_length=3, verbose_name='iata_code')),
                ('latitude', models.FloatField(verbose_name='coordinates')),
                ('longitude', models.FloatField(verbose_name='coordinates')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Continent', verbose_name='continent')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Country', verbose_name='iso_country')),
            ],
        ),
    ]
