# Generated by Django 2.2.10 on 2020-03-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200306_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='dial',
            field=models.TextField(verbose_name='Dial'),
        ),
    ]
